//= require ./app
//= require_self
//= require_tree ./lib
//= require_tree ./helpers
//= require_tree ./animations
//= require ./game/board
//= require ./game/board_pictures
//= require ./game/boot
//= require ./game/credits
//= require ./game/end_game
//= require ./game/logic
//= require ./game/main_menu
//= require ./game/pause_panel
//= require ./game/preloader
//= require ./game/select_level
//= require ./game/tiles_clicks
//= require ./game/game
//= require ./game/main
